### ISSUE TITLE
Texture improvements

### ISSUE THREAD

**Issue by ohtrobinson** [piegfx/Pie#19]
- [x] GL textures seem to use unsigned byte - this means they won't support floating point textures, etc.
- [x] Multisampling textures
- [x] Map textures
- [x] Fix texture update function

**Comment by ohtrobinson** [comment]
GL textures have been fixed - currently untested but it should work fine.

**Comment by ohtrobinson** [comment]
Texture update function has been fixed.

Textures as a whole need testing for both GL and D3D. 2D and Cubemap textures work fine, along with 2D updates, but Cubemap updates are untested, and 1D, 3D, and array textures are entirely untested, alongside manual mipmap uploads, which may require a slight rework of both texture creation & updates.

**Comment by skyebird189** [comment]
Textures are now internally being reworked completely alongside extensive testing.

**Comment by skyebird189** [comment]
Texture rework has been completed - it has passed all tests on both D3D11 and OpenGL.

**Comment by skyebird189** [comment]
I'm going to make multisampling textures a 1.x feature instead of a 1.0 feature so I'll add it to the list of "stuff to do in the future" instead.

**Comment by ohtrobinson** [comment]
For expediency, map textures will not be done in 1.0, instead it will be a 1.x feature. Fortunately, this can easily be done without any breaking changes.
