### ISSUE TITLE
Avoid `GraphicsDevice.CreateOpenGL` from using `IGLContext` in its parameters.

### ISSUE THREAD

**Issue by LeNitrous** [piegfx/Pie#26]
`IGLContext` is from `Silk.NET.Core` which is a third-party library. As `GraphicsDevice.CreateOpenGL` is a public-facing API, it wouldn't be good to leave that exposed. I would propose instead that we pass delegates and let us manually create and manage GL contexts as needed.

**Comment by skyebird189** [comment]
I have been meaning to look into this, although the implementation would be similar, just with a Pie implementation instead of relying on Silk.NET's implementation.

**Comment by skyebird189** [comment]
This has been implemented in 6a0d71a.
