### ISSUE TITLE
Split Graphics API-specific implementations to separate projects.

### ISSUE THREAD

**Issue by LeNitrous** [piegfx/Pie#27]
Currently, all graphics APIs are housed inside the main project.  Although it might be worrying in package size as it will bundle all third-party libraries when being published. It would be preferrable to split each implementation to their own project.

**Comment by skyebird189** [comment]
I've considered this and I've decided against it as it does not produce the API result I am after. I will look into allowing a user to create defines to disable certain backends.

Ultimately I plan to solve this issue by moving most of Pie to native code and writing a .NET wrapper around that.
